### ISSUE TITLE
RuntimeError with python 3.4

### ISSUE THREAD

**Issue by gdchamal** [Gandi/dnsknife#5]
I run this script using python 3.4 and python 3.6 and I encounter a `RuntimeError: dictionary changed size during iteration` with version 3.4 only.

```
#!/bin/env python
import asyncio
import logging
from dnsknife.resolver import Resolver
from dnsknife.exceptions import NoAnswer, BadRcode, DomainNotFound


fqdns = ['chamal.fr']


log = logging.getLogger(__name__)
logging.basicConfig(level=logging.WARN)


@asyncio.coroutine
def test_soa(fqdn):
    ret = 'available'
    with Resolver(timeout=2) as r:
        future_soa = r.query(fqdn, 'SOA')
    try:
        ans = future_soa.get()
        if ans and ans.rrset and ans.rrset.items:
            log.info('found at least {}'.format(ans.rrset))
            ret = 'unavailable'
    except DomainNotFound as exc:
        log.warn('dns says {} is not found'.format(fqdn))
    except NoAnswer as exc:
        pass
    except BadRcode as exc:
        msg = getattr(exc, 'args', ['FAIL'])[0]
        if msg == 'NXDOMAIN':
            log.warn('dns says nxdomain for {}'.format(fqdn))
        else:
            log.warn('dns query got a %r' % exc)
    except Exception as exc:
        log.error('ouch dns fail: %r' % exc)
    log.info('dns check found {} seems {}'.format(fqdn, ret))
    return ret


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    for i in range(0, 10):
        print('#### Iteration {}'.format(i))
        for fqdn in fqdns:
            res = loop.run_until_complete(test_soa(fqdn))
            print('Res for {} is {}'.format(fqdn, res))
    loop.close()
```

Error is : 
```
#### Iteration 0
Traceback (most recent call last):
  File "test_soa.py", line 46, in <module>
    res = loop.run_until_complete(test_soa(fqdn))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "test_soa.py", line 19, in test_soa
    future_soa = r.query(fqdn, 'SOA')
  File "/usr/share/virtualenv/foo/lib/python3.4/site-packages/dnsknife/resolver.py", line 362, in __exit__
    self.poll_loop()
  File "/usr/share/virtualenv/foo/lib/python3.4/site-packages/dnsknife/resolver.py", line 356, in poll_loop
    self.one_poll_loop()
  File "/usr/share/virtualenv/foo/lib/python3.4/site-packages/dnsknife/resolver.py", line 350, in one_poll_loop
    for fd, future in self.futures.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by kalou** [comment]
Hey,
Not sure we support asyncio very well - feedback welcome!

Can you try with the new branch https://github.com/Gandi/dnsknife/tree/kalou/issue5 ?
thanks!
